heat_template_version: 2015-04-30

description: >
  HOT template - sample

parameter_groups:
  - label: Instance information
    description: instance information for the sample stack.
    parameters:
    - image
    - flavor
    - key_name
  - label: Network information
    description: Networking info for the sample stack.
    parameters:
    - private_net
    - public_net

parameters:
  key_name:
    type: string
    description: SSH keypair name
    constraints:
      - custom_constraint: nova.keypair
  image:
    type: string
    description: Image name, limited to ubuntu 14.04 (trusty) images
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    description: Flavor
    constraints:
      - custom_constraint: nova.flavor
  public_net:
    type: string
    description: public network
    default: VLAN3337
  private_net:
    type: string
    description: Private network
    constraints:
      - custom_constraint: neutron.network
 
resources:
  sample-server:
    type: OS::Nova::Server
    properties:
      name: sample-server
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: sample-server_port }
      user_data_format: RAW
      user_data: |
        #cloud-config
        packages:
         - vim

  sample-server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      security_groups: [{ get_resource: sample-security_group }]

  sample-server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: sample-server_port }
      floating_network: { get_param: public_net }

  sample-security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: sample-security_group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

outputs:
  sample-server_private_ip:
    description: IP address of sample server in private network
    value: { get_attr: [ sample-server, first_address ] }
  server1_public_ip:
    description: Floating IP address of sample-server in public network
    value: { get_attr: [ sample-server_floating_ip, floating_ip_address ] }

